-- Seed curated debate articles for moderated discussion (comments API requires article rows)
-- Generated by scripts/generateCuratedSeed.mjs — do not edit by hand

INSERT OR IGNORE INTO articles (
  id, title, category, image_url,
  lede, background, perspectives, evidence, counterpoint, implications, conclusion,
  source_urls, civility, stance_for, stance_against, stance_neutral,
  published_at, verified, hidden, source_type
) VALUES (
  'curated-01',
  'Death Penalty vs. Lifetime Imprisonment',
  'Human Rights',
  'https://picsum.photos/seed/curated-01/960/520',
  'When society confronts heinous crimes, should justice mean permanent incarceration or the ultimate punishment? Advocates of life sentences note that imprisonment is severe yet reversible and avoids the moral burden of state-sanctioned killing.',
  'Pro-death-penalty supporters argue that some crimes are so atrocious that only execution suffices. This debate mixes ethics, deterrence and human rights, and divides public opinion worldwide.',
  'Supporters of one side argue that the status quo fails vulnerable people and that change is overdue. Critics warn that proposed reforms carry unintended consequences, trade-offs, and risks to institutions many rely on.',
  'Researchers, journalists, and advocacy groups cite studies, historical precedents, and real-world experiments — though experts disagree on which evidence matters most and how to interpret it.',
  'The strongest challenge to the prevailing view holds that the opposite approach better protects dignity, stability, or individual liberty — and that quick fixes often ignore deeper structural causes.',
  'Whatever society chooses, the decision will shape law, culture, and everyday life. The outcome may reassure one camp while deepening mistrust in the other.',
  'The debate remains open. Constructive disagreement depends on good-faith argument, credible sources, and willingness to engage the strongest version of the other side.',
  '[{"type":"curated","title":"Polaris curated debate topic","url":"#","domain":"polaris.app"}]',
  63,
  30,
  43,
  27,
  1782831874,
  1, 0, 'curated'
);

INSERT OR IGNORE INTO articles (
  id, title, category, image_url,
  lede, background, perspectives, evidence, counterpoint, implications, conclusion,
  source_urls, civility, stance_for, stance_against, stance_neutral,
  published_at, verified, hidden, source_type
) VALUES (
  'curated-02',
  'Legalizing and Regulating Recreational Drugs',
  'Health & Society',
  'https://picsum.photos/seed/curated-02/960/520',
  'Decades after the "war on drugs," many question whether prohibition has done more harm than good. Supporters of legalization claim that regulation could reduce crime and improve public health, pointing to decriminalization experiments in places like Portugal.',
  'Opponents fear that making substances available, even with warning labels, will increase abuse and societal costs. The issue pits individual freedom against public safety and morality.',
  'Supporters of one side argue that the status quo fails vulnerable people and that change is overdue. Critics warn that proposed reforms carry unintended consequences, trade-offs, and risks to institutions many rely on.',
  'Researchers, journalists, and advocacy groups cite studies, historical precedents, and real-world experiments — though experts disagree on which evidence matters most and how to interpret it.',
  'The strongest challenge to the prevailing view holds that the opposite approach better protects dignity, stability, or individual liberty — and that quick fixes often ignore deeper structural causes.',
  'Whatever society chooses, the decision will shape law, culture, and everyday life. The outcome may reassure one camp while deepening mistrust in the other.',
  'The debate remains open. Constructive disagreement depends on good-faith argument, credible sources, and willingness to engage the strongest version of the other side.',
  '[{"type":"curated","title":"Polaris curated debate topic","url":"#","domain":"polaris.app"}]',
  64,
  31,
  43,
  26,
  1782745474,
  1, 0, 'curated'
);

INSERT OR IGNORE INTO articles (
  id, title, category, image_url,
  lede, background, perspectives, evidence, counterpoint, implications, conclusion,
  source_urls, civility, stance_for, stance_against, stance_neutral,
  published_at, verified, hidden, source_type
) VALUES (
  'curated-03',
  'Euthanasia and Physician-Assisted Death',
  'Health & Society',
  'https://picsum.photos/seed/curated-03/960/520',
  'Is it compassionate to allow terminally ill patients to end their lives, or does legalizing assisted death open a dangerous door? Proponents view euthanasia as a merciful choice for people in unbearable suffering, while critics warn about slippery slopes and moral dangers.',
  'This question sits at the intersection of values, policy, and lived experience. Understanding it requires weighing competing claims about fairness, freedom, and what a good society ought to protect.',
  'Supporters of one side argue that the status quo fails vulnerable people and that change is overdue. Critics warn that proposed reforms carry unintended consequences, trade-offs, and risks to institutions many rely on.',
  'Researchers, journalists, and advocacy groups cite studies, historical precedents, and real-world experiments — though experts disagree on which evidence matters most and how to interpret it.',
  'The strongest challenge to the prevailing view holds that the opposite approach better protects dignity, stability, or individual liberty — and that quick fixes often ignore deeper structural causes.',
  'Whatever society chooses, the decision will shape law, culture, and everyday life. The outcome may reassure one camp while deepening mistrust in the other.',
  'The debate remains open. Constructive disagreement depends on good-faith argument, credible sources, and willingness to engage the strongest version of the other side.',
  '[{"type":"curated","title":"Polaris curated debate topic","url":"#","domain":"polaris.app"}]',
  65,
  32,
  43,
  25,
  1782659074,
  1, 0, 'curated'
);

INSERT OR IGNORE INTO articles (
  id, title, category, image_url,
  lede, background, perspectives, evidence, counterpoint, implications, conclusion,
  source_urls, civility, stance_for, stance_against, stance_neutral,
  published_at, verified, hidden, source_type
) VALUES (
  'curated-04',
  'Compulsory Voting vs. Voluntary Elections',
  'Politics & Governance',
  'https://picsum.photos/seed/curated-04/960/520',
  'Should democracies force citizens to vote? Supporters argue that compulsory voting boosts turnout and ensures leaders represent the entire populace.',
  'Critics see mandated voting as an infringement of personal freedom and worry that uninterested or uninformed voters will dilute electoral quality. The dispute frames voting as civic duty versus voluntary right.',
  'Supporters of one side argue that the status quo fails vulnerable people and that change is overdue. Critics warn that proposed reforms carry unintended consequences, trade-offs, and risks to institutions many rely on.',
  'Researchers, journalists, and advocacy groups cite studies, historical precedents, and real-world experiments — though experts disagree on which evidence matters most and how to interpret it.',
  'The strongest challenge to the prevailing view holds that the opposite approach better protects dignity, stability, or individual liberty — and that quick fixes often ignore deeper structural causes.',
  'Whatever society chooses, the decision will shape law, culture, and everyday life. The outcome may reassure one camp while deepening mistrust in the other.',
  'The debate remains open. Constructive disagreement depends on good-faith argument, credible sources, and willingness to engage the strongest version of the other side.',
  '[{"type":"curated","title":"Polaris curated debate topic","url":"#","domain":"polaris.app"}]',
  66,
  33,
  43,
  24,
  1782572674,
  1, 0, 'curated'
);

INSERT OR IGNORE INTO articles (
  id, title, category, image_url,
  lede, background, perspectives, evidence, counterpoint, implications, conclusion,
  source_urls, civility, stance_for, stance_against, stance_neutral,
  published_at, verified, hidden, source_type
) VALUES (
  'curated-05',
  'Profit Maximization vs. Corporate Social Responsibility',
  'Politics & Governance',
  'https://picsum.photos/seed/curated-05/960/520',
  'Many CEOs claim that a firm''s primary obligation is to its shareholders, citing Milton Friedman''s classic argument. Others insist businesses must also protect the environment, workers and communities even if profits decline.',
  'From sweatshop scandals to eco-friendly initiatives, this debate asks whether greed is good or whether corporations must answer to society.',
  'Supporters of one side argue that the status quo fails vulnerable people and that change is overdue. Critics warn that proposed reforms carry unintended consequences, trade-offs, and risks to institutions many rely on.',
  'Researchers, journalists, and advocacy groups cite studies, historical precedents, and real-world experiments — though experts disagree on which evidence matters most and how to interpret it.',
  'The strongest challenge to the prevailing view holds that the opposite approach better protects dignity, stability, or individual liberty — and that quick fixes often ignore deeper structural causes.',
  'Whatever society chooses, the decision will shape law, culture, and everyday life. The outcome may reassure one camp while deepening mistrust in the other.',
  'The debate remains open. Constructive disagreement depends on good-faith argument, credible sources, and willingness to engage the strongest version of the other side.',
  '[{"type":"curated","title":"Polaris curated debate topic","url":"#","domain":"polaris.app"}]',
  67,
  34,
  44,
  22,
  1782486274,
  1, 0, 'curated'
);

INSERT OR IGNORE INTO articles (
  id, title, category, image_url,
  lede, background, perspectives, evidence, counterpoint, implications, conclusion,
  source_urls, civility, stance_for, stance_against, stance_neutral,
  published_at, verified, hidden, source_type
) VALUES (
  'curated-06',
  'Licensing Parenthood',
  'Health & Society',
  'https://picsum.photos/seed/curated-06/960/520',
  'Should parenting require proof of competence? This provocative topic compares raising a child to driving a car, an activity that affects others and arguably warrants licensing.',
  'Advocates argue that mandatory parenting classes, background checks or financial stability could prevent neglect and abuse. Opponents decry the idea as dystopian, citing government overreach and discrimination.',
  'Supporters of one side argue that the status quo fails vulnerable people and that change is overdue. Critics warn that proposed reforms carry unintended consequences, trade-offs, and risks to institutions many rely on.',
  'Researchers, journalists, and advocacy groups cite studies, historical precedents, and real-world experiments — though experts disagree on which evidence matters most and how to interpret it.',
  'The strongest challenge to the prevailing view holds that the opposite approach better protects dignity, stability, or individual liberty — and that quick fixes often ignore deeper structural causes.',
  'Whatever society chooses, the decision will shape law, culture, and everyday life. The outcome may reassure one camp while deepening mistrust in the other.',
  'The debate remains open. Constructive disagreement depends on good-faith argument, credible sources, and willingness to engage the strongest version of the other side.',
  '[{"type":"curated","title":"Polaris curated debate topic","url":"#","domain":"polaris.app"}]',
  68,
  35,
  44,
  21,
  1782399874,
  1, 0, 'curated'
);

INSERT OR IGNORE INTO articles (
  id, title, category, image_url,
  lede, background, perspectives, evidence, counterpoint, implications, conclusion,
  source_urls, civility, stance_for, stance_against, stance_neutral,
  published_at, verified, hidden, source_type
) VALUES (
  'curated-07',
  'Donald Trump''s Economic Interventionism',
  'Politics & Governance',
  'https://picsum.photos/seed/curated-07/960/520',
  'During the Trump administration, trade wars and heavy-handed policies raised questions about free markets. Supporters of Trump''s approach see tariffs and renegotiated trade deals as necessary to protect American industries.',
  'Critics say this "interventionist" strategy disrupted global commerce and violated laissez-faire principles.',
  'Supporters of one side argue that the status quo fails vulnerable people and that change is overdue. Critics warn that proposed reforms carry unintended consequences, trade-offs, and risks to institutions many rely on.',
  'Researchers, journalists, and advocacy groups cite studies, historical precedents, and real-world experiments — though experts disagree on which evidence matters most and how to interpret it.',
  'The strongest challenge to the prevailing view holds that the opposite approach better protects dignity, stability, or individual liberty — and that quick fixes often ignore deeper structural causes.',
  'Whatever society chooses, the decision will shape law, culture, and everyday life. The outcome may reassure one camp while deepening mistrust in the other.',
  'The debate remains open. Constructive disagreement depends on good-faith argument, credible sources, and willingness to engage the strongest version of the other side.',
  '[{"type":"curated","title":"Polaris curated debate topic","url":"#","domain":"polaris.app"}]',
  69,
  36,
  44,
  20,
  1782313474,
  1, 0, 'curated'
);

INSERT OR IGNORE INTO articles (
  id, title, category, image_url,
  lede, background, perspectives, evidence, counterpoint, implications, conclusion,
  source_urls, civility, stance_for, stance_against, stance_neutral,
  published_at, verified, hidden, source_type
) VALUES (
  'curated-08',
  'Fake-News Removal Within 24 Hours',
  'Technology',
  'https://picsum.photos/seed/curated-08/960/520',
  'Should governments force social-media platforms to delete misinformation on a timer? Supporters view rapid removal as an "emergency brake" to combat viral lies.',
  'Opponents warn that overzealous moderation threatens free speech and could create a slippery slope toward censorship. This clash pits truth and public safety against civil liberties.',
  'Supporters of one side argue that the status quo fails vulnerable people and that change is overdue. Critics warn that proposed reforms carry unintended consequences, trade-offs, and risks to institutions many rely on.',
  'Researchers, journalists, and advocacy groups cite studies, historical precedents, and real-world experiments — though experts disagree on which evidence matters most and how to interpret it.',
  'The strongest challenge to the prevailing view holds that the opposite approach better protects dignity, stability, or individual liberty — and that quick fixes often ignore deeper structural causes.',
  'Whatever society chooses, the decision will shape law, culture, and everyday life. The outcome may reassure one camp while deepening mistrust in the other.',
  'The debate remains open. Constructive disagreement depends on good-faith argument, credible sources, and willingness to engage the strongest version of the other side.',
  '[{"type":"curated","title":"Polaris curated debate topic","url":"#","domain":"polaris.app"}]',
  70,
  37,
  44,
  19,
  1782227074,
  1, 0, 'curated'
);

INSERT OR IGNORE INTO articles (
  id, title, category, image_url,
  lede, background, perspectives, evidence, counterpoint, implications, conclusion,
  source_urls, civility, stance_for, stance_against, stance_neutral,
  published_at, verified, hidden, source_type
) VALUES (
  'curated-09',
  'Prisoner Voting Rights',
  'Human Rights',
  'https://picsum.photos/seed/curated-09/960/520',
  'Can a democracy be truly representative if prisoners cannot vote? This question examines whether incarceration should silence an individual''s political voice.',
  'Advocates note that civic participation aids rehabilitation, while opponents argue that losing voting rights is a valid part of punishment.',
  'Supporters of one side argue that the status quo fails vulnerable people and that change is overdue. Critics warn that proposed reforms carry unintended consequences, trade-offs, and risks to institutions many rely on.',
  'Researchers, journalists, and advocacy groups cite studies, historical precedents, and real-world experiments — though experts disagree on which evidence matters most and how to interpret it.',
  'The strongest challenge to the prevailing view holds that the opposite approach better protects dignity, stability, or individual liberty — and that quick fixes often ignore deeper structural causes.',
  'Whatever society chooses, the decision will shape law, culture, and everyday life. The outcome may reassure one camp while deepening mistrust in the other.',
  'The debate remains open. Constructive disagreement depends on good-faith argument, credible sources, and willingness to engage the strongest version of the other side.',
  '[{"type":"curated","title":"Polaris curated debate topic","url":"#","domain":"polaris.app"}]',
  71,
  38,
  44,
  18,
  1782140674,
  1, 0, 'curated'
);

INSERT OR IGNORE INTO articles (
  id, title, category, image_url,
  lede, background, perspectives, evidence, counterpoint, implications, conclusion,
  source_urls, civility, stance_for, stance_against, stance_neutral,
  published_at, verified, hidden, source_type
) VALUES (
  'curated-10',
  'Punishment vs. Rehabilitation in Prisons',
  'Human Rights',
  'https://picsum.photos/seed/curated-10/960/520',
  'Should prisons primarily penalize offenders or help them rebuild their lives? Those favoring harsh penalties emphasize deterrence and retribution, whereas supporters of rehabilitation believe society benefits more when inmates are educated and given second chances.',
  'This question sits at the intersection of values, policy, and lived experience. Understanding it requires weighing competing claims about fairness, freedom, and what a good society ought to protect.',
  'Supporters of one side argue that the status quo fails vulnerable people and that change is overdue. Critics warn that proposed reforms carry unintended consequences, trade-offs, and risks to institutions many rely on.',
  'Researchers, journalists, and advocacy groups cite studies, historical precedents, and real-world experiments — though experts disagree on which evidence matters most and how to interpret it.',
  'The strongest challenge to the prevailing view holds that the opposite approach better protects dignity, stability, or individual liberty — and that quick fixes often ignore deeper structural causes.',
  'Whatever society chooses, the decision will shape law, culture, and everyday life. The outcome may reassure one camp while deepening mistrust in the other.',
  'The debate remains open. Constructive disagreement depends on good-faith argument, credible sources, and willingness to engage the strongest version of the other side.',
  '[{"type":"curated","title":"Polaris curated debate topic","url":"#","domain":"polaris.app"}]',
  72,
  35,
  45,
  20,
  1782054274,
  1, 0, 'curated'
);

INSERT OR IGNORE INTO articles (
  id, title, category, image_url,
  lede, background, perspectives, evidence, counterpoint, implications, conclusion,
  source_urls, civility, stance_for, stance_against, stance_neutral,
  published_at, verified, hidden, source_type
) VALUES (
  'curated-11',
  'Public Transport vs. Road Infrastructure Funding',
  'Climate & Environment',
  'https://picsum.photos/seed/curated-11/960/520',
  'Should governments invest more in buses, trains and subways, or expand roads for private vehicles? Proponents of public transport funding highlight sustainability and equality, while critics argue that smoother roads are essential for economic growth.',
  'This question sits at the intersection of values, policy, and lived experience. Understanding it requires weighing competing claims about fairness, freedom, and what a good society ought to protect.',
  'Supporters of one side argue that the status quo fails vulnerable people and that change is overdue. Critics warn that proposed reforms carry unintended consequences, trade-offs, and risks to institutions many rely on.',
  'Researchers, journalists, and advocacy groups cite studies, historical precedents, and real-world experiments — though experts disagree on which evidence matters most and how to interpret it.',
  'The strongest challenge to the prevailing view holds that the opposite approach better protects dignity, stability, or individual liberty — and that quick fixes often ignore deeper structural causes.',
  'Whatever society chooses, the decision will shape law, culture, and everyday life. The outcome may reassure one camp while deepening mistrust in the other.',
  'The debate remains open. Constructive disagreement depends on good-faith argument, credible sources, and willingness to engage the strongest version of the other side.',
  '[{"type":"curated","title":"Polaris curated debate topic","url":"#","domain":"polaris.app"}]',
  73,
  36,
  45,
  19,
  1781967874,
  1, 0, 'curated'
);

INSERT OR IGNORE INTO articles (
  id, title, category, image_url,
  lede, background, perspectives, evidence, counterpoint, implications, conclusion,
  source_urls, civility, stance_for, stance_against, stance_neutral,
  published_at, verified, hidden, source_type
) VALUES (
  'curated-12',
  'Monarchy vs. Republic',
  'Politics & Governance',
  'https://picsum.photos/seed/curated-12/960/520',
  'In constitutional monarchies, royal families serve as cultural symbols. Critics argue that full republics with elected heads of state are more democratic and accountable.',
  'Supporters of monarchy value tradition and national identity.',
  'Supporters of one side argue that the status quo fails vulnerable people and that change is overdue. Critics warn that proposed reforms carry unintended consequences, trade-offs, and risks to institutions many rely on.',
  'Researchers, journalists, and advocacy groups cite studies, historical precedents, and real-world experiments — though experts disagree on which evidence matters most and how to interpret it.',
  'The strongest challenge to the prevailing view holds that the opposite approach better protects dignity, stability, or individual liberty — and that quick fixes often ignore deeper structural causes.',
  'Whatever society chooses, the decision will shape law, culture, and everyday life. The outcome may reassure one camp while deepening mistrust in the other.',
  'The debate remains open. Constructive disagreement depends on good-faith argument, credible sources, and willingness to engage the strongest version of the other side.',
  '[{"type":"curated","title":"Polaris curated debate topic","url":"#","domain":"polaris.app"}]',
  74,
  37,
  45,
  18,
  1781881474,
  1, 0, 'curated'
);

INSERT OR IGNORE INTO articles (
  id, title, category, image_url,
  lede, background, perspectives, evidence, counterpoint, implications, conclusion,
  source_urls, civility, stance_for, stance_against, stance_neutral,
  published_at, verified, hidden, source_type
) VALUES (
  'curated-13',
  'Cognitive and Ethical Tests for Political Candidates',
  'Politics & Governance',
  'https://picsum.photos/seed/curated-13/960/520',
  'Should aspiring leaders prove their mental acuity and moral compass before taking office? Advocates say testing could strengthen governance and voter trust.',
  'Opponents warn that mandatory evaluations undermine freedom of choice and could be abused politically.',
  'Supporters of one side argue that the status quo fails vulnerable people and that change is overdue. Critics warn that proposed reforms carry unintended consequences, trade-offs, and risks to institutions many rely on.',
  'Researchers, journalists, and advocacy groups cite studies, historical precedents, and real-world experiments — though experts disagree on which evidence matters most and how to interpret it.',
  'The strongest challenge to the prevailing view holds that the opposite approach better protects dignity, stability, or individual liberty — and that quick fixes often ignore deeper structural causes.',
  'Whatever society chooses, the decision will shape law, culture, and everyday life. The outcome may reassure one camp while deepening mistrust in the other.',
  'The debate remains open. Constructive disagreement depends on good-faith argument, credible sources, and willingness to engage the strongest version of the other side.',
  '[{"type":"curated","title":"Polaris curated debate topic","url":"#","domain":"polaris.app"}]',
  75,
  38,
  45,
  17,
  1781795074,
  1, 0, 'curated'
);

INSERT OR IGNORE INTO articles (
  id, title, category, image_url,
  lede, background, perspectives, evidence, counterpoint, implications, conclusion,
  source_urls, civility, stance_for, stance_against, stance_neutral,
  published_at, verified, hidden, source_type
) VALUES (
  'curated-14',
  'Social Media''s Influencer Culture',
  'Technology',
  'https://picsum.photos/seed/curated-14/960/520',
  'Are influencers positive role models or purveyors of unrealistic standards? This debate explores whether the rise of online personalities benefits society or fuels negative trends.',
  'Some celebrate influencers for democratizing fame; others blame them for promoting consumerism and body-image issues.',
  'Supporters of one side argue that the status quo fails vulnerable people and that change is overdue. Critics warn that proposed reforms carry unintended consequences, trade-offs, and risks to institutions many rely on.',
  'Researchers, journalists, and advocacy groups cite studies, historical precedents, and real-world experiments — though experts disagree on which evidence matters most and how to interpret it.',
  'The strongest challenge to the prevailing view holds that the opposite approach better protects dignity, stability, or individual liberty — and that quick fixes often ignore deeper structural causes.',
  'Whatever society chooses, the decision will shape law, culture, and everyday life. The outcome may reassure one camp while deepening mistrust in the other.',
  'The debate remains open. Constructive disagreement depends on good-faith argument, credible sources, and willingness to engage the strongest version of the other side.',
  '[{"type":"curated","title":"Polaris curated debate topic","url":"#","domain":"polaris.app"}]',
  76,
  39,
  45,
  16,
  1781708674,
  1, 0, 'curated'
);

INSERT OR IGNORE INTO articles (
  id, title, category, image_url,
  lede, background, perspectives, evidence, counterpoint, implications, conclusion,
  source_urls, civility, stance_for, stance_against, stance_neutral,
  published_at, verified, hidden, source_type
) VALUES (
  'curated-15',
  'Hiding Likes and Follows to Protect Mental Health',
  'Technology',
  'https://picsum.photos/seed/curated-15/960/520',
  'Does displaying "likes" on social platforms harm users'' self-esteem? Advocates for hiding engagement metrics believe it could reduce social pressure.',
  'Opponents argue that public metrics drive accountability and engagement. The issue touches on mental health and platform design.',
  'Supporters of one side argue that the status quo fails vulnerable people and that change is overdue. Critics warn that proposed reforms carry unintended consequences, trade-offs, and risks to institutions many rely on.',
  'Researchers, journalists, and advocacy groups cite studies, historical precedents, and real-world experiments — though experts disagree on which evidence matters most and how to interpret it.',
  'The strongest challenge to the prevailing view holds that the opposite approach better protects dignity, stability, or individual liberty — and that quick fixes often ignore deeper structural causes.',
  'Whatever society chooses, the decision will shape law, culture, and everyday life. The outcome may reassure one camp while deepening mistrust in the other.',
  'The debate remains open. Constructive disagreement depends on good-faith argument, credible sources, and willingness to engage the strongest version of the other side.',
  '[{"type":"curated","title":"Polaris curated debate topic","url":"#","domain":"polaris.app"}]',
  77,
  40,
  45,
  15,
  1781622274,
  1, 0, 'curated'
);

INSERT OR IGNORE INTO articles (
  id, title, category, image_url,
  lede, background, perspectives, evidence, counterpoint, implications, conclusion,
  source_urls, civility, stance_for, stance_against, stance_neutral,
  published_at, verified, hidden, source_type
) VALUES (
  'curated-16',
  'Breaking Up Big Tech',
  'Technology',
  'https://picsum.photos/seed/curated-16/960/520',
  'With tech giants dominating markets, some call for antitrust action. Critics of monopolies argue that breaking up big tech would foster competition and consumer choice.',
  'Others warn that fragmentation could hinder innovation and global competitiveness.',
  'Supporters of one side argue that the status quo fails vulnerable people and that change is overdue. Critics warn that proposed reforms carry unintended consequences, trade-offs, and risks to institutions many rely on.',
  'Researchers, journalists, and advocacy groups cite studies, historical precedents, and real-world experiments — though experts disagree on which evidence matters most and how to interpret it.',
  'The strongest challenge to the prevailing view holds that the opposite approach better protects dignity, stability, or individual liberty — and that quick fixes often ignore deeper structural causes.',
  'Whatever society chooses, the decision will shape law, culture, and everyday life. The outcome may reassure one camp while deepening mistrust in the other.',
  'The debate remains open. Constructive disagreement depends on good-faith argument, credible sources, and willingness to engage the strongest version of the other side.',
  '[{"type":"curated","title":"Polaris curated debate topic","url":"#","domain":"polaris.app"}]',
  78,
  41,
  46,
  13,
  1781535874,
  1, 0, 'curated'
);

INSERT OR IGNORE INTO articles (
  id, title, category, image_url,
  lede, background, perspectives, evidence, counterpoint, implications, conclusion,
  source_urls, civility, stance_for, stance_against, stance_neutral,
  published_at, verified, hidden, source_type
) VALUES (
  'curated-17',
  'AI in Debate Activities',
  'Education',
  'https://picsum.photos/seed/curated-17/960/520',
  'As generative AI improves, should it be barred from debating? Purists worry that AI research tools and deepfake voices could erode human-only debate skills.',
  'Others see AI as a practice buddy and fact-checker, comparing bans to forbidding calculators.',
  'Supporters of one side argue that the status quo fails vulnerable people and that change is overdue. Critics warn that proposed reforms carry unintended consequences, trade-offs, and risks to institutions many rely on.',
  'Researchers, journalists, and advocacy groups cite studies, historical precedents, and real-world experiments — though experts disagree on which evidence matters most and how to interpret it.',
  'The strongest challenge to the prevailing view holds that the opposite approach better protects dignity, stability, or individual liberty — and that quick fixes often ignore deeper structural causes.',
  'Whatever society chooses, the decision will shape law, culture, and everyday life. The outcome may reassure one camp while deepening mistrust in the other.',
  'The debate remains open. Constructive disagreement depends on good-faith argument, credible sources, and willingness to engage the strongest version of the other side.',
  '[{"type":"curated","title":"Polaris curated debate topic","url":"#","domain":"polaris.app"}]',
  79,
  42,
  46,
  12,
  1781449474,
  1, 0, 'curated'
);

INSERT OR IGNORE INTO articles (
  id, title, category, image_url,
  lede, background, perspectives, evidence, counterpoint, implications, conclusion,
  source_urls, civility, stance_for, stance_against, stance_neutral,
  published_at, verified, hidden, source_type
) VALUES (
  'curated-18',
  'Parents Accessing Teen Dating Apps',
  'Health & Society',
  'https://picsum.photos/seed/curated-18/960/520',
  'Parents want to protect their children; teenagers want privacy. This topic asks whether parents should have access to their teens'' dating-app accounts.',
  'Proponents emphasize safety and oversight, while opponents argue that snooping undermines trust and autonomy.',
  'Supporters of one side argue that the status quo fails vulnerable people and that change is overdue. Critics warn that proposed reforms carry unintended consequences, trade-offs, and risks to institutions many rely on.',
  'Researchers, journalists, and advocacy groups cite studies, historical precedents, and real-world experiments — though experts disagree on which evidence matters most and how to interpret it.',
  'The strongest challenge to the prevailing view holds that the opposite approach better protects dignity, stability, or individual liberty — and that quick fixes often ignore deeper structural causes.',
  'Whatever society chooses, the decision will shape law, culture, and everyday life. The outcome may reassure one camp while deepening mistrust in the other.',
  'The debate remains open. Constructive disagreement depends on good-faith argument, credible sources, and willingness to engage the strongest version of the other side.',
  '[{"type":"curated","title":"Polaris curated debate topic","url":"#","domain":"polaris.app"}]',
  80,
  43,
  46,
  11,
  1781363074,
  1, 0, 'curated'
);

INSERT OR IGNORE INTO articles (
  id, title, category, image_url,
  lede, background, perspectives, evidence, counterpoint, implications, conclusion,
  source_urls, civility, stance_for, stance_against, stance_neutral,
  published_at, verified, hidden, source_type
) VALUES (
  'curated-19',
  'Is Online Dating Ruining the Dating Scene?',
  'Health & Society',
  'https://picsum.photos/seed/curated-19/960/520',
  'Dating apps have reshaped relationships. Critics worry they encourage superficial interactions and commodify romance.',
  'Defenders see them as tools for connection in a busy world. The debate reflects generational and cultural differences in courtship.',
  'Supporters of one side argue that the status quo fails vulnerable people and that change is overdue. Critics warn that proposed reforms carry unintended consequences, trade-offs, and risks to institutions many rely on.',
  'Researchers, journalists, and advocacy groups cite studies, historical precedents, and real-world experiments — though experts disagree on which evidence matters most and how to interpret it.',
  'The strongest challenge to the prevailing view holds that the opposite approach better protects dignity, stability, or individual liberty — and that quick fixes often ignore deeper structural causes.',
  'Whatever society chooses, the decision will shape law, culture, and everyday life. The outcome may reassure one camp while deepening mistrust in the other.',
  'The debate remains open. Constructive disagreement depends on good-faith argument, credible sources, and willingness to engage the strongest version of the other side.',
  '[{"type":"curated","title":"Polaris curated debate topic","url":"#","domain":"polaris.app"}]',
  81,
  44,
  46,
  10,
  1781276674,
  1, 0, 'curated'
);

INSERT OR IGNORE INTO articles (
  id, title, category, image_url,
  lede, background, perspectives, evidence, counterpoint, implications, conclusion,
  source_urls, civility, stance_for, stance_against, stance_neutral,
  published_at, verified, hidden, source_type
) VALUES (
  'curated-20',
  'Does Social Media Do More Harm Than Good?',
  'Technology',
  'https://picsum.photos/seed/curated-20/960/520',
  'Perhaps the platform''s biggest question, this topic weighs social media''s benefits (connection, information) against its harms (polarization, misinformation, addiction). The debate invites a broad examination of how platforms shape society.',
  'This question sits at the intersection of values, policy, and lived experience. Understanding it requires weighing competing claims about fairness, freedom, and what a good society ought to protect.',
  'Supporters of one side argue that the status quo fails vulnerable people and that change is overdue. Critics warn that proposed reforms carry unintended consequences, trade-offs, and risks to institutions many rely on.',
  'Researchers, journalists, and advocacy groups cite studies, historical precedents, and real-world experiments — though experts disagree on which evidence matters most and how to interpret it.',
  'The strongest challenge to the prevailing view holds that the opposite approach better protects dignity, stability, or individual liberty — and that quick fixes often ignore deeper structural causes.',
  'Whatever society chooses, the decision will shape law, culture, and everyday life. The outcome may reassure one camp while deepening mistrust in the other.',
  'The debate remains open. Constructive disagreement depends on good-faith argument, credible sources, and willingness to engage the strongest version of the other side.',
  '[{"type":"curated","title":"Polaris curated debate topic","url":"#","domain":"polaris.app"}]',
  82,
  41,
  47,
  12,
  1781190274,
  1, 0, 'curated'
);

INSERT OR IGNORE INTO articles (
  id, title, category, image_url,
  lede, background, perspectives, evidence, counterpoint, implications, conclusion,
  source_urls, civility, stance_for, stance_against, stance_neutral,
  published_at, verified, hidden, source_type
) VALUES (
  'curated-21',
  'Is Social Media Addiction a Public-Health Crisis?',
  'Health & Society',
  'https://picsum.photos/seed/curated-21/960/520',
  'Some researchers liken heavy social-media use to substance addiction, citing dopamine spikes and mental-health issues. Critics argue that "addiction" is an exaggerated term and that blame lies in individuals'' self-control.',
  'Governments and platforms face pressure to treat this as a health issue.',
  'Supporters of one side argue that the status quo fails vulnerable people and that change is overdue. Critics warn that proposed reforms carry unintended consequences, trade-offs, and risks to institutions many rely on.',
  'Researchers, journalists, and advocacy groups cite studies, historical precedents, and real-world experiments — though experts disagree on which evidence matters most and how to interpret it.',
  'The strongest challenge to the prevailing view holds that the opposite approach better protects dignity, stability, or individual liberty — and that quick fixes often ignore deeper structural causes.',
  'Whatever society chooses, the decision will shape law, culture, and everyday life. The outcome may reassure one camp while deepening mistrust in the other.',
  'The debate remains open. Constructive disagreement depends on good-faith argument, credible sources, and willingness to engage the strongest version of the other side.',
  '[{"type":"curated","title":"Polaris curated debate topic","url":"#","domain":"polaris.app"}]',
  83,
  42,
  47,
  11,
  1781103874,
  1, 0, 'curated'
);

INSERT OR IGNORE INTO articles (
  id, title, category, image_url,
  lede, background, perspectives, evidence, counterpoint, implications, conclusion,
  source_urls, civility, stance_for, stance_against, stance_neutral,
  published_at, verified, hidden, source_type
) VALUES (
  'curated-22',
  'Do Social Movements Need to Go Viral?',
  'Politics & Governance',
  'https://picsum.photos/seed/curated-22/960/520',
  'From the Arab Spring to #MeToo, virality has amplified activism. This debate questions whether causes can succeed without trending online.',
  'Some activists say that going viral is essential for awareness; others argue that quiet, local organizing remains crucial.',
  'Supporters of one side argue that the status quo fails vulnerable people and that change is overdue. Critics warn that proposed reforms carry unintended consequences, trade-offs, and risks to institutions many rely on.',
  'Researchers, journalists, and advocacy groups cite studies, historical precedents, and real-world experiments — though experts disagree on which evidence matters most and how to interpret it.',
  'The strongest challenge to the prevailing view holds that the opposite approach better protects dignity, stability, or individual liberty — and that quick fixes often ignore deeper structural causes.',
  'Whatever society chooses, the decision will shape law, culture, and everyday life. The outcome may reassure one camp while deepening mistrust in the other.',
  'The debate remains open. Constructive disagreement depends on good-faith argument, credible sources, and willingness to engage the strongest version of the other side.',
  '[{"type":"curated","title":"Polaris curated debate topic","url":"#","domain":"polaris.app"}]',
  84,
  43,
  47,
  10,
  1781017474,
  1, 0, 'curated'
);

INSERT OR IGNORE INTO articles (
  id, title, category, image_url,
  lede, background, perspectives, evidence, counterpoint, implications, conclusion,
  source_urls, civility, stance_for, stance_against, stance_neutral,
  published_at, verified, hidden, source_type
) VALUES (
  'curated-23',
  'Character Development vs. Academics in Schools',
  'Education',
  'https://picsum.photos/seed/curated-23/960/520',
  'Should early education prioritize empathy, resilience and ethics alongside reading and math? Proponents of social-emotional learning argue that cooperation and self-control are critical for long-term success.',
  'Traditionalists counter that basic academics must come first. The debate seeks a balance between virtue and GPA.',
  'Supporters of one side argue that the status quo fails vulnerable people and that change is overdue. Critics warn that proposed reforms carry unintended consequences, trade-offs, and risks to institutions many rely on.',
  'Researchers, journalists, and advocacy groups cite studies, historical precedents, and real-world experiments — though experts disagree on which evidence matters most and how to interpret it.',
  'The strongest challenge to the prevailing view holds that the opposite approach better protects dignity, stability, or individual liberty — and that quick fixes often ignore deeper structural causes.',
  'Whatever society chooses, the decision will shape law, culture, and everyday life. The outcome may reassure one camp while deepening mistrust in the other.',
  'The debate remains open. Constructive disagreement depends on good-faith argument, credible sources, and willingness to engage the strongest version of the other side.',
  '[{"type":"curated","title":"Polaris curated debate topic","url":"#","domain":"polaris.app"}]',
  85,
  44,
  47,
  10,
  1780931074,
  1, 0, 'curated'
);

INSERT OR IGNORE INTO articles (
  id, title, category, image_url,
  lede, background, perspectives, evidence, counterpoint, implications, conclusion,
  source_urls, civility, stance_for, stance_against, stance_neutral,
  published_at, verified, hidden, source_type
) VALUES (
  'curated-24',
  'Abolishing Grades for Personalized Growth Reports',
  'Education',
  'https://picsum.photos/seed/curated-24/960/520',
  'Replacing report-card letters with narrative feedback could encourage growth mindsets and reduce test anxiety. Critics worry about subjectivity and the complications this poses for college admissions.',
  'The issue challenges long-standing evaluation systems.',
  'Supporters of one side argue that the status quo fails vulnerable people and that change is overdue. Critics warn that proposed reforms carry unintended consequences, trade-offs, and risks to institutions many rely on.',
  'Researchers, journalists, and advocacy groups cite studies, historical precedents, and real-world experiments — though experts disagree on which evidence matters most and how to interpret it.',
  'The strongest challenge to the prevailing view holds that the opposite approach better protects dignity, stability, or individual liberty — and that quick fixes often ignore deeper structural causes.',
  'Whatever society chooses, the decision will shape law, culture, and everyday life. The outcome may reassure one camp while deepening mistrust in the other.',
  'The debate remains open. Constructive disagreement depends on good-faith argument, credible sources, and willingness to engage the strongest version of the other side.',
  '[{"type":"curated","title":"Polaris curated debate topic","url":"#","domain":"polaris.app"}]',
  86,
  45,
  47,
  10,
  1780844674,
  1, 0, 'curated'
);

INSERT OR IGNORE INTO articles (
  id, title, category, image_url,
  lede, background, perspectives, evidence, counterpoint, implications, conclusion,
  source_urls, civility, stance_for, stance_against, stance_neutral,
  published_at, verified, hidden, source_type
) VALUES (
  'curated-25',
  'Blockchain-Certified Micro-Credentials vs. Traditional Degrees',
  'Education',
  'https://picsum.photos/seed/curated-25/960/520',
  'In an age of MOOCs and crypto technology, some propose replacing degrees with secure digital badges. Proponents say micro-credentials can be more current and job-relevant, preventing résumé fraud.',
  'Skeptics doubt whether employers will value badges over established diplomas.',
  'Supporters of one side argue that the status quo fails vulnerable people and that change is overdue. Critics warn that proposed reforms carry unintended consequences, trade-offs, and risks to institutions many rely on.',
  'Researchers, journalists, and advocacy groups cite studies, historical precedents, and real-world experiments — though experts disagree on which evidence matters most and how to interpret it.',
  'The strongest challenge to the prevailing view holds that the opposite approach better protects dignity, stability, or individual liberty — and that quick fixes often ignore deeper structural causes.',
  'Whatever society chooses, the decision will shape law, culture, and everyday life. The outcome may reassure one camp while deepening mistrust in the other.',
  'The debate remains open. Constructive disagreement depends on good-faith argument, credible sources, and willingness to engage the strongest version of the other side.',
  '[{"type":"curated","title":"Polaris curated debate topic","url":"#","domain":"polaris.app"}]',
  87,
  46,
  47,
  10,
  1780758274,
  1, 0, 'curated'
);

INSERT OR IGNORE INTO articles (
  id, title, category, image_url,
  lede, background, perspectives, evidence, counterpoint, implications, conclusion,
  source_urls, civility, stance_for, stance_against, stance_neutral,
  published_at, verified, hidden, source_type
) VALUES (
  'curated-26',
  'Merit-Based Admissions vs. Diversity Quotas',
  'Education',
  'https://picsum.photos/seed/curated-26/960/520',
  'College admissions officers face a dilemma: select the best scores or assemble a diverse class? Merit advocates warn that quotas may undermine standards, while diversity supporters argue that proactive measures correct historic inequities.',
  'The debate intertwines fairness, equity and educational outcomes.',
  'Supporters of one side argue that the status quo fails vulnerable people and that change is overdue. Critics warn that proposed reforms carry unintended consequences, trade-offs, and risks to institutions many rely on.',
  'Researchers, journalists, and advocacy groups cite studies, historical precedents, and real-world experiments — though experts disagree on which evidence matters most and how to interpret it.',
  'The strongest challenge to the prevailing view holds that the opposite approach better protects dignity, stability, or individual liberty — and that quick fixes often ignore deeper structural causes.',
  'Whatever society chooses, the decision will shape law, culture, and everyday life. The outcome may reassure one camp while deepening mistrust in the other.',
  'The debate remains open. Constructive disagreement depends on good-faith argument, credible sources, and willingness to engage the strongest version of the other side.',
  '[{"type":"curated","title":"Polaris curated debate topic","url":"#","domain":"polaris.app"}]',
  88,
  47,
  47,
  10,
  1780671874,
  1, 0, 'curated'
);

INSERT OR IGNORE INTO articles (
  id, title, category, image_url,
  lede, background, perspectives, evidence, counterpoint, implications, conclusion,
  source_urls, civility, stance_for, stance_against, stance_neutral,
  published_at, verified, hidden, source_type
) VALUES (
  'curated-27',
  'Banning Smartphones for Children Under 13',
  'Education',
  'https://picsum.photos/seed/curated-27/960/520',
  'With concerns about screen addiction and cyberbullying, some argue for a hard age limit on smartphone ownership. Supporters imagine kids playing outside more, whereas critics say technology literacy is essential and bans infringe on parental choice.',
  'This question sits at the intersection of values, policy, and lived experience. Understanding it requires weighing competing claims about fairness, freedom, and what a good society ought to protect.',
  'Supporters of one side argue that the status quo fails vulnerable people and that change is overdue. Critics warn that proposed reforms carry unintended consequences, trade-offs, and risks to institutions many rely on.',
  'Researchers, journalists, and advocacy groups cite studies, historical precedents, and real-world experiments — though experts disagree on which evidence matters most and how to interpret it.',
  'The strongest challenge to the prevailing view holds that the opposite approach better protects dignity, stability, or individual liberty — and that quick fixes often ignore deeper structural causes.',
  'Whatever society chooses, the decision will shape law, culture, and everyday life. The outcome may reassure one camp while deepening mistrust in the other.',
  'The debate remains open. Constructive disagreement depends on good-faith argument, credible sources, and willingness to engage the strongest version of the other side.',
  '[{"type":"curated","title":"Polaris curated debate topic","url":"#","domain":"polaris.app"}]',
  89,
  48,
  48,
  10,
  1780585474,
  1, 0, 'curated'
);

INSERT OR IGNORE INTO articles (
  id, title, category, image_url,
  lede, background, perspectives, evidence, counterpoint, implications, conclusion,
  source_urls, civility, stance_for, stance_against, stance_neutral,
  published_at, verified, hidden, source_type
) VALUES (
  'curated-28',
  'Parents Still Paying Education Taxes After Children Graduate',
  'Education',
  'https://picsum.photos/seed/curated-28/960/520',
  'Education funding typically comes from property or income taxes. Should parents stop paying once their kids finish school?',
  'Community advocates respond that public education benefits everyone and that today''s students become tomorrow''s doctors, leaders and taxpayers.',
  'Supporters of one side argue that the status quo fails vulnerable people and that change is overdue. Critics warn that proposed reforms carry unintended consequences, trade-offs, and risks to institutions many rely on.',
  'Researchers, journalists, and advocacy groups cite studies, historical precedents, and real-world experiments — though experts disagree on which evidence matters most and how to interpret it.',
  'The strongest challenge to the prevailing view holds that the opposite approach better protects dignity, stability, or individual liberty — and that quick fixes often ignore deeper structural causes.',
  'Whatever society chooses, the decision will shape law, culture, and everyday life. The outcome may reassure one camp while deepening mistrust in the other.',
  'The debate remains open. Constructive disagreement depends on good-faith argument, credible sources, and willingness to engage the strongest version of the other side.',
  '[{"type":"curated","title":"Polaris curated debate topic","url":"#","domain":"polaris.app"}]',
  62,
  49,
  48,
  10,
  1780499074,
  1, 0, 'curated'
);

INSERT OR IGNORE INTO articles (
  id, title, category, image_url,
  lede, background, perspectives, evidence, counterpoint, implications, conclusion,
  source_urls, civility, stance_for, stance_against, stance_neutral,
  published_at, verified, hidden, source_type
) VALUES (
  'curated-29',
  'Using AI Tools like ChatGPT for Homework',
  'Education',
  'https://picsum.photos/seed/curated-29/960/520',
  'AI can help students brainstorm and edit, but at what cost? Supporters see AI as a powerful tutor that improves learning.',
  'Critics warn that over-reliance leads to shallow understanding and raises academic-integrity concerns. Schools are rewriting honor codes to address this new reality.',
  'Supporters of one side argue that the status quo fails vulnerable people and that change is overdue. Critics warn that proposed reforms carry unintended consequences, trade-offs, and risks to institutions many rely on.',
  'Researchers, journalists, and advocacy groups cite studies, historical precedents, and real-world experiments — though experts disagree on which evidence matters most and how to interpret it.',
  'The strongest challenge to the prevailing view holds that the opposite approach better protects dignity, stability, or individual liberty — and that quick fixes often ignore deeper structural causes.',
  'Whatever society chooses, the decision will shape law, culture, and everyday life. The outcome may reassure one camp while deepening mistrust in the other.',
  'The debate remains open. Constructive disagreement depends on good-faith argument, credible sources, and willingness to engage the strongest version of the other side.',
  '[{"type":"curated","title":"Polaris curated debate topic","url":"#","domain":"polaris.app"}]',
  63,
  50,
  48,
  10,
  1780412674,
  1, 0, 'curated'
);

INSERT OR IGNORE INTO articles (
  id, title, category, image_url,
  lede, background, perspectives, evidence, counterpoint, implications, conclusion,
  source_urls, civility, stance_for, stance_against, stance_neutral,
  published_at, verified, hidden, source_type
) VALUES (
  'curated-30',
  'Animals in Research and Animal Rights',
  'Science',
  'https://picsum.photos/seed/curated-30/960/520',
  'Animal testing has led to lifesaving medical breakthroughs, yet it raises profound ethical concerns. This debate asks whether potential benefits justify harming sentient creatures.',
  'It also examines whether humane alternatives can replace traditional practices.',
  'Supporters of one side argue that the status quo fails vulnerable people and that change is overdue. Critics warn that proposed reforms carry unintended consequences, trade-offs, and risks to institutions many rely on.',
  'Researchers, journalists, and advocacy groups cite studies, historical precedents, and real-world experiments — though experts disagree on which evidence matters most and how to interpret it.',
  'The strongest challenge to the prevailing view holds that the opposite approach better protects dignity, stability, or individual liberty — and that quick fixes often ignore deeper structural causes.',
  'Whatever society chooses, the decision will shape law, culture, and everyday life. The outcome may reassure one camp while deepening mistrust in the other.',
  'The debate remains open. Constructive disagreement depends on good-faith argument, credible sources, and willingness to engage the strongest version of the other side.',
  '[{"type":"curated","title":"Polaris curated debate topic","url":"#","domain":"polaris.app"}]',
  64,
  47,
  49,
  10,
  1780326274,
  1, 0, 'curated'
);

INSERT OR IGNORE INTO articles (
  id, title, category, image_url,
  lede, background, perspectives, evidence, counterpoint, implications, conclusion,
  source_urls, civility, stance_for, stance_against, stance_neutral,
  published_at, verified, hidden, source_type
) VALUES (
  'curated-31',
  'Should we normalize quitting instead of "never give up"?',
  'Health & Society',
  'https://picsum.photos/seed/curated-31/960/520',
  'A debate weighing whether quitting can prevent burnout and redirect energy, or if it erodes resilience and perseverance.',
  'This question sits at the intersection of values, policy, and lived experience. Understanding it requires weighing competing claims about fairness, freedom, and what a good society ought to protect.',
  'Supporters of one side argue that the status quo fails vulnerable people and that change is overdue. Critics warn that proposed reforms carry unintended consequences, trade-offs, and risks to institutions many rely on.',
  'Researchers, journalists, and advocacy groups cite studies, historical precedents, and real-world experiments — though experts disagree on which evidence matters most and how to interpret it.',
  'The strongest challenge to the prevailing view holds that the opposite approach better protects dignity, stability, or individual liberty — and that quick fixes often ignore deeper structural causes.',
  'Whatever society chooses, the decision will shape law, culture, and everyday life. The outcome may reassure one camp while deepening mistrust in the other.',
  'The debate remains open. Constructive disagreement depends on good-faith argument, credible sources, and willingness to engage the strongest version of the other side.',
  '[{"type":"curated","title":"Polaris curated debate topic","url":"#","domain":"polaris.app"}]',
  65,
  48,
  49,
  10,
  1780239874,
  1, 0, 'curated'
);

INSERT OR IGNORE INTO articles (
  id, title, category, image_url,
  lede, background, perspectives, evidence, counterpoint, implications, conclusion,
  source_urls, civility, stance_for, stance_against, stance_neutral,
  published_at, verified, hidden, source_type
) VALUES (
  'curated-32',
  'Do commemorative months actually raise awareness or are they just symbolic?',
  'Human Rights',
  'https://picsum.photos/seed/curated-32/960/520',
  'Examines whether months like Black History Month bring visibility and education or are performative gestures without lasting impact.',
  'This question sits at the intersection of values, policy, and lived experience. Understanding it requires weighing competing claims about fairness, freedom, and what a good society ought to protect.',
  'Supporters of one side argue that the status quo fails vulnerable people and that change is overdue. Critics warn that proposed reforms carry unintended consequences, trade-offs, and risks to institutions many rely on.',
  'Researchers, journalists, and advocacy groups cite studies, historical precedents, and real-world experiments — though experts disagree on which evidence matters most and how to interpret it.',
  'The strongest challenge to the prevailing view holds that the opposite approach better protects dignity, stability, or individual liberty — and that quick fixes often ignore deeper structural causes.',
  'Whatever society chooses, the decision will shape law, culture, and everyday life. The outcome may reassure one camp while deepening mistrust in the other.',
  'The debate remains open. Constructive disagreement depends on good-faith argument, credible sources, and willingness to engage the strongest version of the other side.',
  '[{"type":"curated","title":"Polaris curated debate topic","url":"#","domain":"polaris.app"}]',
  66,
  49,
  49,
  10,
  1780153474,
  1, 0, 'curated'
);

INSERT OR IGNORE INTO articles (
  id, title, category, image_url,
  lede, background, perspectives, evidence, counterpoint, implications, conclusion,
  source_urls, civility, stance_for, stance_against, stance_neutral,
  published_at, verified, hidden, source_type
) VALUES (
  'curated-33',
  'Should toy companies stop marketing toys specifically to boys or girls?',
  'Education',
  'https://picsum.photos/seed/curated-33/960/520',
  'Questions whether gender-based marketing limits children''s interests and suggests a shift toward gender-neutral products.',
  'This question sits at the intersection of values, policy, and lived experience. Understanding it requires weighing competing claims about fairness, freedom, and what a good society ought to protect.',
  'Supporters of one side argue that the status quo fails vulnerable people and that change is overdue. Critics warn that proposed reforms carry unintended consequences, trade-offs, and risks to institutions many rely on.',
  'Researchers, journalists, and advocacy groups cite studies, historical precedents, and real-world experiments — though experts disagree on which evidence matters most and how to interpret it.',
  'The strongest challenge to the prevailing view holds that the opposite approach better protects dignity, stability, or individual liberty — and that quick fixes often ignore deeper structural causes.',
  'Whatever society chooses, the decision will shape law, culture, and everyday life. The outcome may reassure one camp while deepening mistrust in the other.',
  'The debate remains open. Constructive disagreement depends on good-faith argument, credible sources, and willingness to engage the strongest version of the other side.',
  '[{"type":"curated","title":"Polaris curated debate topic","url":"#","domain":"polaris.app"}]',
  67,
  50,
  49,
  10,
  1780067074,
  1, 0, 'curated'
);

INSERT OR IGNORE INTO articles (
  id, title, category, image_url,
  lede, background, perspectives, evidence, counterpoint, implications, conclusion,
  source_urls, civility, stance_for, stance_against, stance_neutral,
  published_at, verified, hidden, source_type
) VALUES (
  'curated-34',
  'Do universities need to stop pretending all degrees have equal value in the job market?',
  'Education',
  'https://picsum.photos/seed/curated-34/960/520',
  'Looks at whether different degrees provide comparable employment outcomes and whether higher education should be more transparent about returns.',
  'This question sits at the intersection of values, policy, and lived experience. Understanding it requires weighing competing claims about fairness, freedom, and what a good society ought to protect.',
  'Supporters of one side argue that the status quo fails vulnerable people and that change is overdue. Critics warn that proposed reforms carry unintended consequences, trade-offs, and risks to institutions many rely on.',
  'Researchers, journalists, and advocacy groups cite studies, historical precedents, and real-world experiments — though experts disagree on which evidence matters most and how to interpret it.',
  'The strongest challenge to the prevailing view holds that the opposite approach better protects dignity, stability, or individual liberty — and that quick fixes often ignore deeper structural causes.',
  'Whatever society chooses, the decision will shape law, culture, and everyday life. The outcome may reassure one camp while deepening mistrust in the other.',
  'The debate remains open. Constructive disagreement depends on good-faith argument, credible sources, and willingness to engage the strongest version of the other side.',
  '[{"type":"curated","title":"Polaris curated debate topic","url":"#","domain":"polaris.app"}]',
  68,
  51,
  49,
  10,
  1779980674,
  1, 0, 'curated'
);

INSERT OR IGNORE INTO articles (
  id, title, category, image_url,
  lede, background, perspectives, evidence, counterpoint, implications, conclusion,
  source_urls, civility, stance_for, stance_against, stance_neutral,
  published_at, verified, hidden, source_type
) VALUES (
  'curated-35',
  'Does criminalizing low-value survival crimes (shoplifting, fare-dodging) do more harm than good?',
  'Human Rights',
  'https://picsum.photos/seed/curated-35/960/520',
  'Challenges whether punishing poverty-driven offenses merely traps people in poverty instead of addressing root causes.',
  'This question sits at the intersection of values, policy, and lived experience. Understanding it requires weighing competing claims about fairness, freedom, and what a good society ought to protect.',
  'Supporters of one side argue that the status quo fails vulnerable people and that change is overdue. Critics warn that proposed reforms carry unintended consequences, trade-offs, and risks to institutions many rely on.',
  'Researchers, journalists, and advocacy groups cite studies, historical precedents, and real-world experiments — though experts disagree on which evidence matters most and how to interpret it.',
  'The strongest challenge to the prevailing view holds that the opposite approach better protects dignity, stability, or individual liberty — and that quick fixes often ignore deeper structural causes.',
  'Whatever society chooses, the decision will shape law, culture, and everyday life. The outcome may reassure one camp while deepening mistrust in the other.',
  'The debate remains open. Constructive disagreement depends on good-faith argument, credible sources, and willingness to engage the strongest version of the other side.',
  '[{"type":"curated","title":"Polaris curated debate topic","url":"#","domain":"polaris.app"}]',
  69,
  52,
  49,
  10,
  1779894274,
  1, 0, 'curated'
);

INSERT OR IGNORE INTO articles (
  id, title, category, image_url,
  lede, background, perspectives, evidence, counterpoint, implications, conclusion,
  source_urls, civility, stance_for, stance_against, stance_neutral,
  published_at, verified, hidden, source_type
) VALUES (
  'curated-36',
  'Should religion have no place in politics?',
  'Religion & Ethics',
  'https://picsum.photos/seed/curated-36/960/520',
  'Explores the boundaries between faith and political power and whether secularism ensures fair representation in pluralistic societies.',
  'This question sits at the intersection of values, policy, and lived experience. Understanding it requires weighing competing claims about fairness, freedom, and what a good society ought to protect.',
  'Supporters of one side argue that the status quo fails vulnerable people and that change is overdue. Critics warn that proposed reforms carry unintended consequences, trade-offs, and risks to institutions many rely on.',
  'Researchers, journalists, and advocacy groups cite studies, historical precedents, and real-world experiments — though experts disagree on which evidence matters most and how to interpret it.',
  'The strongest challenge to the prevailing view holds that the opposite approach better protects dignity, stability, or individual liberty — and that quick fixes often ignore deeper structural causes.',
  'Whatever society chooses, the decision will shape law, culture, and everyday life. The outcome may reassure one camp while deepening mistrust in the other.',
  'The debate remains open. Constructive disagreement depends on good-faith argument, credible sources, and willingness to engage the strongest version of the other side.',
  '[{"type":"curated","title":"Polaris curated debate topic","url":"#","domain":"polaris.app"}]',
  70,
  28,
  49,
  23,
  1779807874,
  1, 0, 'curated'
);

INSERT OR IGNORE INTO articles (
  id, title, category, image_url,
  lede, background, perspectives, evidence, counterpoint, implications, conclusion,
  source_urls, civility, stance_for, stance_against, stance_neutral,
  published_at, verified, hidden, source_type
) VALUES (
  'curated-37',
  'Should single-sex spaces be defined by biological sex or gender identity?',
  'Human Rights',
  'https://picsum.photos/seed/curated-37/960/520',
  'Considers evolving definitions of gender in sports, shelters and prisons, and the tension between inclusion, privacy and safety.',
  'This question sits at the intersection of values, policy, and lived experience. Understanding it requires weighing competing claims about fairness, freedom, and what a good society ought to protect.',
  'Supporters of one side argue that the status quo fails vulnerable people and that change is overdue. Critics warn that proposed reforms carry unintended consequences, trade-offs, and risks to institutions many rely on.',
  'Researchers, journalists, and advocacy groups cite studies, historical precedents, and real-world experiments — though experts disagree on which evidence matters most and how to interpret it.',
  'The strongest challenge to the prevailing view holds that the opposite approach better protects dignity, stability, or individual liberty — and that quick fixes often ignore deeper structural causes.',
  'Whatever society chooses, the decision will shape law, culture, and everyday life. The outcome may reassure one camp while deepening mistrust in the other.',
  'The debate remains open. Constructive disagreement depends on good-faith argument, credible sources, and willingness to engage the strongest version of the other side.',
  '[{"type":"curated","title":"Polaris curated debate topic","url":"#","domain":"polaris.app"}]',
  71,
  29,
  49,
  22,
  1779721474,
  1, 0, 'curated'
);

INSERT OR IGNORE INTO articles (
  id, title, category, image_url,
  lede, background, perspectives, evidence, counterpoint, implications, conclusion,
  source_urls, civility, stance_for, stance_against, stance_neutral,
  published_at, verified, hidden, source_type
) VALUES (
  'curated-38',
  'Are mental-health disorders being overdiagnosed in young adults?',
  'Health & Society',
  'https://picsum.photos/seed/curated-38/960/520',
  'Debates whether rising diagnoses of anxiety, depression and ADHD reflect better recognition or an over-medicalization of normal distress.',
  'This question sits at the intersection of values, policy, and lived experience. Understanding it requires weighing competing claims about fairness, freedom, and what a good society ought to protect.',
  'Supporters of one side argue that the status quo fails vulnerable people and that change is overdue. Critics warn that proposed reforms carry unintended consequences, trade-offs, and risks to institutions many rely on.',
  'Researchers, journalists, and advocacy groups cite studies, historical precedents, and real-world experiments — though experts disagree on which evidence matters most and how to interpret it.',
  'The strongest challenge to the prevailing view holds that the opposite approach better protects dignity, stability, or individual liberty — and that quick fixes often ignore deeper structural causes.',
  'Whatever society chooses, the decision will shape law, culture, and everyday life. The outcome may reassure one camp while deepening mistrust in the other.',
  'The debate remains open. Constructive disagreement depends on good-faith argument, credible sources, and willingness to engage the strongest version of the other side.',
  '[{"type":"curated","title":"Polaris curated debate topic","url":"#","domain":"polaris.app"}]',
  72,
  30,
  50,
  20,
  1779635074,
  1, 0, 'curated'
);

INSERT OR IGNORE INTO articles (
  id, title, category, image_url,
  lede, background, perspectives, evidence, counterpoint, implications, conclusion,
  source_urls, civility, stance_for, stance_against, stance_neutral,
  published_at, verified, hidden, source_type
) VALUES (
  'curated-39',
  'Should emotional harm be treated as seriously as physical harm in law?',
  'Human Rights',
  'https://picsum.photos/seed/curated-39/960/520',
  'Asks whether legal systems should give equal weight to emotional and physical injuries when assessing damages and justice.',
  'This question sits at the intersection of values, policy, and lived experience. Understanding it requires weighing competing claims about fairness, freedom, and what a good society ought to protect.',
  'Supporters of one side argue that the status quo fails vulnerable people and that change is overdue. Critics warn that proposed reforms carry unintended consequences, trade-offs, and risks to institutions many rely on.',
  'Researchers, journalists, and advocacy groups cite studies, historical precedents, and real-world experiments — though experts disagree on which evidence matters most and how to interpret it.',
  'The strongest challenge to the prevailing view holds that the opposite approach better protects dignity, stability, or individual liberty — and that quick fixes often ignore deeper structural causes.',
  'Whatever society chooses, the decision will shape law, culture, and everyday life. The outcome may reassure one camp while deepening mistrust in the other.',
  'The debate remains open. Constructive disagreement depends on good-faith argument, credible sources, and willingness to engage the strongest version of the other side.',
  '[{"type":"curated","title":"Polaris curated debate topic","url":"#","domain":"polaris.app"}]',
  73,
  31,
  50,
  19,
  1779548674,
  1, 0, 'curated'
);

INSERT OR IGNORE INTO articles (
  id, title, category, image_url,
  lede, background, perspectives, evidence, counterpoint, implications, conclusion,
  source_urls, civility, stance_for, stance_against, stance_neutral,
  published_at, verified, hidden, source_type
) VALUES (
  'curated-40',
  'Is disaster tourism ethical?',
  'Religion & Ethics',
  'https://picsum.photos/seed/curated-40/960/520',
  'Weighs whether visiting sites of tragedy educates and memorializes or commodifies suffering for "dark tourism".',
  'This question sits at the intersection of values, policy, and lived experience. Understanding it requires weighing competing claims about fairness, freedom, and what a good society ought to protect.',
  'Supporters of one side argue that the status quo fails vulnerable people and that change is overdue. Critics warn that proposed reforms carry unintended consequences, trade-offs, and risks to institutions many rely on.',
  'Researchers, journalists, and advocacy groups cite studies, historical precedents, and real-world experiments — though experts disagree on which evidence matters most and how to interpret it.',
  'The strongest challenge to the prevailing view holds that the opposite approach better protects dignity, stability, or individual liberty — and that quick fixes often ignore deeper structural causes.',
  'Whatever society chooses, the decision will shape law, culture, and everyday life. The outcome may reassure one camp while deepening mistrust in the other.',
  'The debate remains open. Constructive disagreement depends on good-faith argument, credible sources, and willingness to engage the strongest version of the other side.',
  '[{"type":"curated","title":"Polaris curated debate topic","url":"#","domain":"polaris.app"}]',
  74,
  28,
  51,
  21,
  1779462274,
  1, 0, 'curated'
);

INSERT OR IGNORE INTO articles (
  id, title, category, image_url,
  lede, background, perspectives, evidence, counterpoint, implications, conclusion,
  source_urls, civility, stance_for, stance_against, stance_neutral,
  published_at, verified, hidden, source_type
) VALUES (
  'curated-41',
  'Is AI making people less intelligent?',
  'Technology',
  'https://picsum.photos/seed/curated-41/960/520',
  'Considers whether automation of thinking tasks and constant info streams erode our depth of thought or simply shift which skills matter.',
  'This question sits at the intersection of values, policy, and lived experience. Understanding it requires weighing competing claims about fairness, freedom, and what a good society ought to protect.',
  'Supporters of one side argue that the status quo fails vulnerable people and that change is overdue. Critics warn that proposed reforms carry unintended consequences, trade-offs, and risks to institutions many rely on.',
  'Researchers, journalists, and advocacy groups cite studies, historical precedents, and real-world experiments — though experts disagree on which evidence matters most and how to interpret it.',
  'The strongest challenge to the prevailing view holds that the opposite approach better protects dignity, stability, or individual liberty — and that quick fixes often ignore deeper structural causes.',
  'Whatever society chooses, the decision will shape law, culture, and everyday life. The outcome may reassure one camp while deepening mistrust in the other.',
  'The debate remains open. Constructive disagreement depends on good-faith argument, credible sources, and willingness to engage the strongest version of the other side.',
  '[{"type":"curated","title":"Polaris curated debate topic","url":"#","domain":"polaris.app"}]',
  75,
  29,
  51,
  20,
  1779375874,
  1, 0, 'curated'
);

INSERT OR IGNORE INTO articles (
  id, title, category, image_url,
  lede, background, perspectives, evidence, counterpoint, implications, conclusion,
  source_urls, civility, stance_for, stance_against, stance_neutral,
  published_at, verified, hidden, source_type
) VALUES (
  'curated-42',
  'Can we create a universally objective definition of right and wrong?',
  'Religion & Ethics',
  'https://picsum.photos/seed/curated-42/960/520',
  'Surveys philosophical efforts from ancient codes to modern debates, asking if morality is a universal truth or culturally constructed.',
  'This question sits at the intersection of values, policy, and lived experience. Understanding it requires weighing competing claims about fairness, freedom, and what a good society ought to protect.',
  'Supporters of one side argue that the status quo fails vulnerable people and that change is overdue. Critics warn that proposed reforms carry unintended consequences, trade-offs, and risks to institutions many rely on.',
  'Researchers, journalists, and advocacy groups cite studies, historical precedents, and real-world experiments — though experts disagree on which evidence matters most and how to interpret it.',
  'The strongest challenge to the prevailing view holds that the opposite approach better protects dignity, stability, or individual liberty — and that quick fixes often ignore deeper structural causes.',
  'Whatever society chooses, the decision will shape law, culture, and everyday life. The outcome may reassure one camp while deepening mistrust in the other.',
  'The debate remains open. Constructive disagreement depends on good-faith argument, credible sources, and willingness to engage the strongest version of the other side.',
  '[{"type":"curated","title":"Polaris curated debate topic","url":"#","domain":"polaris.app"}]',
  76,
  30,
  51,
  19,
  1779289474,
  1, 0, 'curated'
);

INSERT OR IGNORE INTO articles (
  id, title, category, image_url,
  lede, background, perspectives, evidence, counterpoint, implications, conclusion,
  source_urls, civility, stance_for, stance_against, stance_neutral,
  published_at, verified, hidden, source_type
) VALUES (
  'curated-43',
  'Is cancel culture a form of censorship?',
  'Politics & Governance',
  'https://picsum.photos/seed/curated-43/960/520',
  'Questions whether public backlash holds people accountable or unjustly silences speech, balancing free expression with social responsibility.',
  'This question sits at the intersection of values, policy, and lived experience. Understanding it requires weighing competing claims about fairness, freedom, and what a good society ought to protect.',
  'Supporters of one side argue that the status quo fails vulnerable people and that change is overdue. Critics warn that proposed reforms carry unintended consequences, trade-offs, and risks to institutions many rely on.',
  'Researchers, journalists, and advocacy groups cite studies, historical precedents, and real-world experiments — though experts disagree on which evidence matters most and how to interpret it.',
  'The strongest challenge to the prevailing view holds that the opposite approach better protects dignity, stability, or individual liberty — and that quick fixes often ignore deeper structural causes.',
  'Whatever society chooses, the decision will shape law, culture, and everyday life. The outcome may reassure one camp while deepening mistrust in the other.',
  'The debate remains open. Constructive disagreement depends on good-faith argument, credible sources, and willingness to engage the strongest version of the other side.',
  '[{"type":"curated","title":"Polaris curated debate topic","url":"#","domain":"polaris.app"}]',
  77,
  31,
  51,
  18,
  1779203074,
  1, 0, 'curated'
);

INSERT OR IGNORE INTO articles (
  id, title, category, image_url,
  lede, background, perspectives, evidence, counterpoint, implications, conclusion,
  source_urls, civility, stance_for, stance_against, stance_neutral,
  published_at, verified, hidden, source_type
) VALUES (
  'curated-44',
  'Is bullying a natural part of youth development?',
  'Education',
  'https://picsum.photos/seed/curated-44/960/520',
  'Explores whether rough peer interactions "build character" or normalize cruelty, and whether empathy can replace domination as a rite of passage.',
  'This question sits at the intersection of values, policy, and lived experience. Understanding it requires weighing competing claims about fairness, freedom, and what a good society ought to protect.',
  'Supporters of one side argue that the status quo fails vulnerable people and that change is overdue. Critics warn that proposed reforms carry unintended consequences, trade-offs, and risks to institutions many rely on.',
  'Researchers, journalists, and advocacy groups cite studies, historical precedents, and real-world experiments — though experts disagree on which evidence matters most and how to interpret it.',
  'The strongest challenge to the prevailing view holds that the opposite approach better protects dignity, stability, or individual liberty — and that quick fixes often ignore deeper structural causes.',
  'Whatever society chooses, the decision will shape law, culture, and everyday life. The outcome may reassure one camp while deepening mistrust in the other.',
  'The debate remains open. Constructive disagreement depends on good-faith argument, credible sources, and willingness to engage the strongest version of the other side.',
  '[{"type":"curated","title":"Polaris curated debate topic","url":"#","domain":"polaris.app"}]',
  78,
  32,
  51,
  17,
  1779116674,
  1, 0, 'curated'
);

INSERT OR IGNORE INTO articles (
  id, title, category, image_url,
  lede, background, perspectives, evidence, counterpoint, implications, conclusion,
  source_urls, civility, stance_for, stance_against, stance_neutral,
  published_at, verified, hidden, source_type
) VALUES (
  'curated-45',
  'Are truth and justice human-made constructs?',
  'Religion & Ethics',
  'https://picsum.photos/seed/curated-45/960/520',
  'Delves into moral relativism and social constructivism, asking if these ideals exist beyond human interpretation.',
  'This question sits at the intersection of values, policy, and lived experience. Understanding it requires weighing competing claims about fairness, freedom, and what a good society ought to protect.',
  'Supporters of one side argue that the status quo fails vulnerable people and that change is overdue. Critics warn that proposed reforms carry unintended consequences, trade-offs, and risks to institutions many rely on.',
  'Researchers, journalists, and advocacy groups cite studies, historical precedents, and real-world experiments — though experts disagree on which evidence matters most and how to interpret it.',
  'The strongest challenge to the prevailing view holds that the opposite approach better protects dignity, stability, or individual liberty — and that quick fixes often ignore deeper structural causes.',
  'Whatever society chooses, the decision will shape law, culture, and everyday life. The outcome may reassure one camp while deepening mistrust in the other.',
  'The debate remains open. Constructive disagreement depends on good-faith argument, credible sources, and willingness to engage the strongest version of the other side.',
  '[{"type":"curated","title":"Polaris curated debate topic","url":"#","domain":"polaris.app"}]',
  79,
  33,
  51,
  16,
  1782918274,
  1, 0, 'curated'
);

INSERT OR IGNORE INTO articles (
  id, title, category, image_url,
  lede, background, perspectives, evidence, counterpoint, implications, conclusion,
  source_urls, civility, stance_for, stance_against, stance_neutral,
  published_at, verified, hidden, source_type
) VALUES (
  'curated-46',
  'Should American football be banned?',
  'Health & Society',
  'https://picsum.photos/seed/curated-46/960/520',
  'Debates whether the sport''s cultural significance outweighs concerns about player safety and long-term health risks.',
  'This question sits at the intersection of values, policy, and lived experience. Understanding it requires weighing competing claims about fairness, freedom, and what a good society ought to protect.',
  'Supporters of one side argue that the status quo fails vulnerable people and that change is overdue. Critics warn that proposed reforms carry unintended consequences, trade-offs, and risks to institutions many rely on.',
  'Researchers, journalists, and advocacy groups cite studies, historical precedents, and real-world experiments — though experts disagree on which evidence matters most and how to interpret it.',
  'The strongest challenge to the prevailing view holds that the opposite approach better protects dignity, stability, or individual liberty — and that quick fixes often ignore deeper structural causes.',
  'Whatever society chooses, the decision will shape law, culture, and everyday life. The outcome may reassure one camp while deepening mistrust in the other.',
  'The debate remains open. Constructive disagreement depends on good-faith argument, credible sources, and willingness to engage the strongest version of the other side.',
  '[{"type":"curated","title":"Polaris curated debate topic","url":"#","domain":"polaris.app"}]',
  80,
  34,
  51,
  15,
  1782831874,
  1, 0, 'curated'
);

INSERT OR IGNORE INTO articles (
  id, title, category, image_url,
  lede, background, perspectives, evidence, counterpoint, implications, conclusion,
  source_urls, civility, stance_for, stance_against, stance_neutral,
  published_at, verified, hidden, source_type
) VALUES (
  'curated-47',
  'Should history classes include mandatory units on colonialism and slavery?',
  'Education',
  'https://picsum.photos/seed/curated-47/960/520',
  'Discusses whether curricula should ensure in-depth coverage of colonialism and the transatlantic slave trade to confront legacies of oppression.',
  'This question sits at the intersection of values, policy, and lived experience. Understanding it requires weighing competing claims about fairness, freedom, and what a good society ought to protect.',
  'Supporters of one side argue that the status quo fails vulnerable people and that change is overdue. Critics warn that proposed reforms carry unintended consequences, trade-offs, and risks to institutions many rely on.',
  'Researchers, journalists, and advocacy groups cite studies, historical precedents, and real-world experiments — though experts disagree on which evidence matters most and how to interpret it.',
  'The strongest challenge to the prevailing view holds that the opposite approach better protects dignity, stability, or individual liberty — and that quick fixes often ignore deeper structural causes.',
  'Whatever society chooses, the decision will shape law, culture, and everyday life. The outcome may reassure one camp while deepening mistrust in the other.',
  'The debate remains open. Constructive disagreement depends on good-faith argument, credible sources, and willingness to engage the strongest version of the other side.',
  '[{"type":"curated","title":"Polaris curated debate topic","url":"#","domain":"polaris.app"}]',
  81,
  35,
  51,
  14,
  1782745474,
  1, 0, 'curated'
);

INSERT OR IGNORE INTO articles (
  id, title, category, image_url,
  lede, background, perspectives, evidence, counterpoint, implications, conclusion,
  source_urls, civility, stance_for, stance_against, stance_neutral,
  published_at, verified, hidden, source_type
) VALUES (
  'curated-48',
  'Should cultural appropriation ever be considered a compliment?',
  'Religion & Ethics',
  'https://picsum.photos/seed/curated-48/960/520',
  'Differentiates between respectful cultural exchange and appropriation, questioning when borrowing traditions honors or exploits marginalized cultures.',
  'This question sits at the intersection of values, policy, and lived experience. Understanding it requires weighing competing claims about fairness, freedom, and what a good society ought to protect.',
  'Supporters of one side argue that the status quo fails vulnerable people and that change is overdue. Critics warn that proposed reforms carry unintended consequences, trade-offs, and risks to institutions many rely on.',
  'Researchers, journalists, and advocacy groups cite studies, historical precedents, and real-world experiments — though experts disagree on which evidence matters most and how to interpret it.',
  'The strongest challenge to the prevailing view holds that the opposite approach better protects dignity, stability, or individual liberty — and that quick fixes often ignore deeper structural causes.',
  'Whatever society chooses, the decision will shape law, culture, and everyday life. The outcome may reassure one camp while deepening mistrust in the other.',
  'The debate remains open. Constructive disagreement depends on good-faith argument, credible sources, and willingness to engage the strongest version of the other side.',
  '[{"type":"curated","title":"Polaris curated debate topic","url":"#","domain":"polaris.app"}]',
  82,
  36,
  51,
  13,
  1782659074,
  1, 0, 'curated'
);

INSERT OR IGNORE INTO articles (
  id, title, category, image_url,
  lede, background, perspectives, evidence, counterpoint, implications, conclusion,
  source_urls, civility, stance_for, stance_against, stance_neutral,
  published_at, verified, hidden, source_type
) VALUES (
  'curated-49',
  'Would celebrities be better off without media coaches?',
  'Technology',
  'https://picsum.photos/seed/curated-49/960/520',
  'Considers whether media training protects stars and prevents scandals or turns them into inauthentic performances.',
  'This question sits at the intersection of values, policy, and lived experience. Understanding it requires weighing competing claims about fairness, freedom, and what a good society ought to protect.',
  'Supporters of one side argue that the status quo fails vulnerable people and that change is overdue. Critics warn that proposed reforms carry unintended consequences, trade-offs, and risks to institutions many rely on.',
  'Researchers, journalists, and advocacy groups cite studies, historical precedents, and real-world experiments — though experts disagree on which evidence matters most and how to interpret it.',
  'The strongest challenge to the prevailing view holds that the opposite approach better protects dignity, stability, or individual liberty — and that quick fixes often ignore deeper structural causes.',
  'Whatever society chooses, the decision will shape law, culture, and everyday life. The outcome may reassure one camp while deepening mistrust in the other.',
  'The debate remains open. Constructive disagreement depends on good-faith argument, credible sources, and willingness to engage the strongest version of the other side.',
  '[{"type":"curated","title":"Polaris curated debate topic","url":"#","domain":"polaris.app"}]',
  83,
  37,
  52,
  11,
  1782572674,
  1, 0, 'curated'
);

INSERT OR IGNORE INTO articles (
  id, title, category, image_url,
  lede, background, perspectives, evidence, counterpoint, implications, conclusion,
  source_urls, civility, stance_for, stance_against, stance_neutral,
  published_at, verified, hidden, source_type
) VALUES (
  'curated-50',
  'Should organ markets be legalized to reduce transplant shortages?',
  'Health & Society',
  'https://picsum.photos/seed/curated-50/960/520',
  'Tackles whether a regulated organ-sale system could increase supply and save lives or would exploit the poor and commodify the human body.',
  'This question sits at the intersection of values, policy, and lived experience. Understanding it requires weighing competing claims about fairness, freedom, and what a good society ought to protect.',
  'Supporters of one side argue that the status quo fails vulnerable people and that change is overdue. Critics warn that proposed reforms carry unintended consequences, trade-offs, and risks to institutions many rely on.',
  'Researchers, journalists, and advocacy groups cite studies, historical precedents, and real-world experiments — though experts disagree on which evidence matters most and how to interpret it.',
  'The strongest challenge to the prevailing view holds that the opposite approach better protects dignity, stability, or individual liberty — and that quick fixes often ignore deeper structural causes.',
  'Whatever society chooses, the decision will shape law, culture, and everyday life. The outcome may reassure one camp while deepening mistrust in the other.',
  'The debate remains open. Constructive disagreement depends on good-faith argument, credible sources, and willingness to engage the strongest version of the other side.',
  '[{"type":"curated","title":"Polaris curated debate topic","url":"#","domain":"polaris.app"}]',
  84,
  34,
  28,
  38,
  1782486274,
  1, 0, 'curated'
);
