#!/usr/bin/env node
/**
 * Generates worker/migrations/005_seed_curated_debates.sql from src/data/curatedDebates.js
 * Run: node scripts/generateCuratedSeed.mjs
 */
import { writeFileSync, mkdirSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'
import { CURATED_DEBATES } from '../src/data/curatedDebates.js'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const outPath = join(root, 'worker/migrations/005_seed_curated_debates.sql')

function sqlEscape(s) {
  return String(s ?? '').replace(/'/g, "''")
}

const lines = [
  '-- Seed curated debate articles for moderated discussion (comments API requires article rows)',
  '-- Generated by scripts/generateCuratedSeed.mjs — do not edit by hand',
  '',
]

for (const d of CURATED_DEBATES) {
  const a = d.article
  const sources = JSON.stringify(d.sources ?? [])
  const now = Math.floor(Date.now() / 1000) - 86400 * (parseInt(d.id.replace('curated-', ''), 10) % 45)
  lines.push(`INSERT OR IGNORE INTO articles (
  id, title, category, image_url,
  lede, background, perspectives, evidence, counterpoint, implications, conclusion,
  source_urls, civility, stance_for, stance_against, stance_neutral,
  published_at, verified, hidden, source_type
) VALUES (
  '${sqlEscape(d.id)}',
  '${sqlEscape(d.title)}',
  '${sqlEscape(d.topicArea)}',
  '${sqlEscape(d.imageUrl)}',
  '${sqlEscape(a.lede)}',
  '${sqlEscape(a.background)}',
  '${sqlEscape(a.perspectives)}',
  '${sqlEscape(a.evidence)}',
  '${sqlEscape(a.counterpoint)}',
  '${sqlEscape(a.implications)}',
  '${sqlEscape(a.conclusion)}',
  '${sqlEscape(sources)}',
  ${d.civility ?? 75},
  ${d.stanceDistribution.for},
  ${d.stanceDistribution.against},
  ${d.stanceDistribution.neutral},
  ${now},
  1, 0, 'curated'
);`)
  lines.push('')
}

writeFileSync(outPath, lines.join('\n'))
console.log(`Wrote ${CURATED_DEBATES.length} inserts to ${outPath}`)

const tsPath = join(root, 'worker/src/data/curatedSeeds.ts')
mkdirSync(dirname(tsPath), { recursive: true })
const tsEntries = CURATED_DEBATES.map((d) => {
  const a = d.article
  const sources = JSON.stringify(d.sources ?? [])
  const publishedAt =
    Math.floor(Date.now() / 1000) - 86400 * (parseInt(d.id.replace('curated-', ''), 10) % 45)
  return `  ${JSON.stringify(d.id)}: {
    id: ${JSON.stringify(d.id)},
    title: ${JSON.stringify(d.title)},
    category: ${JSON.stringify(d.topicArea)},
    imageUrl: ${JSON.stringify(d.imageUrl)},
    lede: ${JSON.stringify(a.lede)},
    background: ${JSON.stringify(a.background)},
    perspectives: ${JSON.stringify(a.perspectives)},
    evidence: ${JSON.stringify(a.evidence)},
    counterpoint: ${JSON.stringify(a.counterpoint)},
    implications: ${JSON.stringify(a.implications)},
    conclusion: ${JSON.stringify(a.conclusion)},
    sourceUrls: ${JSON.stringify(sources)},
    civility: ${d.civility ?? 75},
    stanceFor: ${d.stanceDistribution.for},
    stanceAgainst: ${d.stanceDistribution.against},
    stanceNeutral: ${d.stanceDistribution.neutral},
    publishedAt: ${publishedAt},
  }`
})

const tsContent = `// Auto-generated by scripts/generateCuratedSeed.mjs — do not edit by hand

export interface CuratedSeed {
  id: string;
  title: string;
  category: string;
  imageUrl: string;
  lede: string;
  background: string;
  perspectives: string;
  evidence: string;
  counterpoint: string;
  implications: string;
  conclusion: string;
  sourceUrls: string;
  civility: number;
  stanceFor: number;
  stanceAgainst: number;
  stanceNeutral: number;
  publishedAt: number;
}

export const CURATED_SEEDS: Record<string, CuratedSeed> = {
${tsEntries.join(',\n')},
};
`

writeFileSync(tsPath, tsContent)
console.log(`Wrote ${CURATED_DEBATES.length} seeds to ${tsPath}`)
