#!/usr/bin/env node
/**
 * Generates worker/migrations/005_seed_curated_debates.sql from src/data/curatedDebates.js
 * Run: node scripts/generateCuratedSeed.mjs
 */
import { writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'
import { CURATED_DEBATES } from '../src/data/curatedDebates.js'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const outPath = join(root, 'worker/migrations/005_seed_curated_debates.sql')

function sqlEscape(s) {
  return String(s ?? '').replace(/'/g, "''")
}

const lines = [
  '-- Seed curated debate articles for moderated discussion (comments API requires article rows)',
  '-- Generated by scripts/generateCuratedSeed.mjs — do not edit by hand',
  '',
]

for (const d of CURATED_DEBATES) {
  const a = d.article
  const sources = JSON.stringify(d.sources ?? [])
  const now = Math.floor(Date.now() / 1000) - 86400 * (parseInt(d.id.replace('curated-', ''), 10) % 45)
  lines.push(`INSERT OR IGNORE INTO articles (
  id, title, category, image_url,
  lede, background, perspectives, evidence, counterpoint, implications, conclusion,
  source_urls, civility, stance_for, stance_against, stance_neutral,
  published_at, verified, hidden, source_type
) VALUES (
  '${sqlEscape(d.id)}',
  '${sqlEscape(d.title)}',
  '${sqlEscape(d.topicArea)}',
  '${sqlEscape(d.imageUrl)}',
  '${sqlEscape(a.lede)}',
  '${sqlEscape(a.background)}',
  '${sqlEscape(a.perspectives)}',
  '${sqlEscape(a.evidence)}',
  '${sqlEscape(a.counterpoint)}',
  '${sqlEscape(a.implications)}',
  '${sqlEscape(a.conclusion)}',
  '${sqlEscape(sources)}',
  ${d.civility ?? 75},
  ${d.stanceDistribution.for},
  ${d.stanceDistribution.against},
  ${d.stanceDistribution.neutral},
  ${now},
  1, 0, 'curated'
);`)
  lines.push('')
}

writeFileSync(outPath, lines.join('\n'))
console.log(`Wrote ${CURATED_DEBATES.length} inserts to ${outPath}`)
